# Generated by Django 4.0.5 on 2022-09-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_department_emp_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='name',
        ),
    ]
